### ISSUE TITLE
Latest jsonvalidate throws "SyntaxError: Use of const in strict mode."

### ISSUE THREAD

**Issue by LTLA** [ropensci/jsonvalidate#52]
The recent **jsonvalidate** update (1.3.1) on CRAN introduces... something... that causes this error:

```r
jsonvalidate::json_validate("asdasdasd")
## Error in context_eval(join(src), private$context, serialize) :
##  SyntaxError: Use of const in strict mode.

traceback()
## 8: stop(structure(list(message = "SyntaxError: Use of const in strict mode.",
##        call = context_eval(join(src), private$context, serialize),
##        cppstack = NULL), class = c("std::invalid_argument", "C++Error",
##    "error", "condition")))
## 7: context_eval(join(src), private$context, serialize)
## 6: get_str_output(context_eval(join(src), private$context, serialize))
## 5: evaluate_js(readLines(file, encoding = "UTF-8", warn = FALSE))
## 4: ct$source(system.file("bundle.js", package = "jsonvalidate"))
## 3: jsonvalidate_js()
## 2: json_validator(schema, engine, reference = reference, strict = strict)
## 1: jsonvalidate::json_validate("asdasdasd")
```

It occurs regardless of what the arguments are, because it's happening during the loading of **jsonvalidate**'s `bundle.js`. I'd also guess that it depends on the version of the V8 library; this problem occurs on my HPC servers where `V8::engine_info` reports 3.14.5.9, while my laptop reports 9.1.269.36 and has no such problems.

**Comment by arnejohannesholmin** [comment]
Hi, Thanks for this useful package. 

I am using jsonvalidate to validate a JSON file in the following package: [RstoxFramework](https://github.com/StoXProject/RstoxFramework) Checks have been failing run on Ubuntu, Mac and Windows over the last week, as seen here: [142](https://github.com/StoXProject/RstoxFramework/pull/142) The checks first failed on Ubuntu and Mac, then on Windows with R 3.6 and the latest R, and then this morning on Windows with R 4.0. 

On Ubuntu I get the same <<SyntaxError: Use of const in strict mode.>> as reported in this issue. But on Mac and Windows I get <<error: While reading '(string)' > '"'>>. The  output from V8::engine_info() is 3.14.5.9 for Ubuntu, 6.2.414.50 for Windows and 8.7.220.29 for Mac.

Is there a time frame on this being fixed on CRAN. Pressure is increasing on my side..

**Comment by richfitz** [comment]
Can you please try the fix as in [this comment](https://github.com/ropensci/jsonvalidate/issues/52#issuecomment-952693889) and let me know if it works.

I aim to submit to CRAN tomorrow once Jeroen is back and we can look at the other CRAN complaint. After that, it's up to them as to whether they accept it

**Comment by arnejohannesholmin** [comment]
I tested installing the fix in the [check-full.yaml](https://github.com/StoXProject/RstoxFramework/blob/develop/.github/workflows/check-full.yaml) (line 125), but problem is still there.

**Comment by richfitz** [comment]
Thanks - that looks like it might be a different problem, your failed builds show:

```
Error: Error: package or namespace load failed for ‘RstoxFramework’:
 .onLoad failed in loadNamespace() for 'RstoxFramework', details:
  call: NULL
  error: While reading '(string)' > '"'
Did not find schema file '"'
Error: Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/runner/work/RstoxFramework/RstoxFramework/check/RstoxFramework.Rcheck/RstoxFramework’
```

The machines you have there overlap considerably with the ones that we're using on jsonvalidate's own tests

**Comment by arnejohannesholmin** [comment]
Ah, I see. The remaining error is something different. Brilliant, then I will fix that error and wait for the new jsonvalidate on CRAN. Thanks.

**Comment by richfitz** [comment]
This is updated on CRAN now, with any luck it will stay there.
