### ISSUE TITLE
Appveyor webhook

### ISSUE THREAD

**Issue by maelle** [ropensci/jsonvalidate#9]
:wave: @richfitz!

Appveyor deliveries are failing cf  

You'll need to email team@appveyor.com with the following info about the latest delivery (that's what they asked me for for other repos)
X-GitHub-Delivery: 94473386-1c0f-11e8-838a-23e941ac6c29
Time: 2018-02-27 23:43:07

Thanks!

**Comment by richfitz** [comment]
Done - thanks Maëlle!

**Comment by richfitz** [comment]
removed the webhook :fire:
